# Generated by Django 4.0.3 on 2022-07-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_order_item_order_order_order_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item_add_ons',
            name='order_item',
        ),
        migrations.AddField(
            model_name='order_item',
            name='order_item_add_ones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.order_item_add_ons'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
